name: gunluk_planlayici
description: "planner"

publish_to: 'none'


version: 1.1.0+16

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  uuid: ^4.3.3
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0

  cupertino_icons: ^1.0.8

  provider: ^6.1.5
  flutter_local_notifications: ^17.2.1 
  timezone: ^0.9.4 
  flutter_timezone: ^4.1.1
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  flutter_phoenix: ^1.1.1
  audioplayers: ^6.5.0
  flutter_background_service: ^5.1.0
  permission_handler: ^12.0.1
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.8

  flutter_native_splash: ^2.4.6

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#05071F"
  adaptive_icon_foreground: "assets/logo/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#05071F"
  image: assets/logo/logosplash.png
  android_12:
    color: "#05071F"
    image: assets/logo/logosplash.png
  ios: true